### ISSUE TITLE
CPU load steadily increases with destroyed instances.

### ISSUE THREAD

**Issue by ColonelJustice** [skymen/trailRenderer#2]
Since at least 2.0.0.8, I believe with the introduction of Z-following, there seems to be a cleanup problem when the trail object gets destroyed. 
Behavior CPU usage spikes when a following instance destroyed. 
It only affects the CPU cycles when it's attached to another object, also it ramps up the more instances got destroyed, making the experience laggy later on to unplayable after 1000 or so instances got destroyed (in my use case, the behavior is used for bullet trails). Checking the z-order option on attachment is no difference, it has the described impact either way.

Simple test:
![image](https://github.com/skymen/trailRenderer/assets/160029739/7cae0cc5-5edd-4557-b4af-7a63b22bff60)

After 5 seconds:
![image](https://github.com/skymen/trailRenderer/assets/160029739/deb30e35-72a1-4af8-8abb-1200af1668e0)

After 20 seconds:

![image](https://github.com/skymen/trailRenderer/assets/160029739/5bb6a474-cec6-44fc-8302-3015cf7cc399)

And so on.

The effect is not present in 2.0.0.0.

**Comment by skymen** [comment]
Hello,

Can you send me a zip of a minimal reproduction project so I can look into it?
I cannot reproduce it on my end by doing the same thing as the screenshot

**Comment by ColonelJustice** [comment]
Here you are (addon is bundled):

[Trailtest.zip](https://github.com/skymen/trailRenderer/files/14280212/Trailtest.zip)

**Comment by ColonelJustice** [comment]
I think it's related to delayed destruction actions.
I did another test where the condition is simply on each tick -> create, then destroy immediately. CPU usage is stable in this scenario.

**Comment by skymen** [comment]
I can reproduce this. It's a weird issue. I'll try to understand what's happening

**Comment by ColonelJustice** [comment]
Hi, any luck with this?

**Comment by skymen** [comment]
Hi, sorry i've been extremely busy recently and could not spend as much time as I wanted working on addons. This is still on my list, I will try to fix it as soon as I can but I can't give a proper timeline

**Comment by skymen** [comment]
Oh my god, I've finally figured out what was wrong...........

I just pushed an update, can you try and see if that fixed it for you? @ColonelJustice

**Comment by bilgekaan** [comment]
It seems fixed for me. Thank you so much!!

**Comment by ColonelJustice** [comment]
Works like a charm. Thank you!
